# config.py

# Twitter App credentials

CONSUMER_KEY = 'LbQsdixQsq0YIJtXEFRtQACmO'
CONSUMER_SECRET = 'aAeAYsd4IUpTccJVcdmOYyQg2wShqzPJIeW35ThR0yHUE9zfe0'
ACCESS_TOKEN_KEY = '3357450011-khX3jqWUPJfckVomtZpWgbJVDaidqMPodKHM79L'
ACCESS_TOKEN_SECRET = 'jETOtrrLg7CEt4jQ0C0cWRcr4zukDa8pdz6kOLbBAn2Xg'